# coding: utf-8

"""
    onelens-backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from onelens_backend_client.models.response_get_policy_template_packs_response import ResponseGetPolicyTemplatePacksResponse

class TestResponseGetPolicyTemplatePacksResponse(unittest.TestCase):
    """ResponseGetPolicyTemplatePacksResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseGetPolicyTemplatePacksResponse:
        """Test ResponseGetPolicyTemplatePacksResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseGetPolicyTemplatePacksResponse`
        """
        model = ResponseGetPolicyTemplatePacksResponse()
        if include_optional:
            return ResponseGetPolicyTemplatePacksResponse(
                data = onelens_backend_client.models.get_policy_template_packs_response.GetPolicyTemplatePacksResponse(
                    pagination = null, 
                    policy_template_packs = [
                        onelens_backend_client.models.policy_template_pack.PolicyTemplatePack(
                            alias = '', 
                            category = null, 
                            provider = null, 
                            details = null, 
                            id = '', 
                            state = null, )
                        ], ),
                message = ''
            )
        else:
            return ResponseGetPolicyTemplatePacksResponse(
                data = onelens_backend_client.models.get_policy_template_packs_response.GetPolicyTemplatePacksResponse(
                    pagination = null, 
                    policy_template_packs = [
                        onelens_backend_client.models.policy_template_pack.PolicyTemplatePack(
                            alias = '', 
                            category = null, 
                            provider = null, 
                            details = null, 
                            id = '', 
                            state = null, )
                        ], ),
        )
        """

    def testResponseGetPolicyTemplatePacksResponse(self):
        """Test ResponseGetPolicyTemplatePacksResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
