# coding: utf-8

"""
    onelens-backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.user_tenant_api import UserTenantApi


class TestUserTenantApi(unittest.TestCase):
    """UserTenantApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserTenantApi()

    def tearDown(self) -> None:
        pass

    def test_create_user_tenant_mapping_v1_users_tenant_mapping_post(self) -> None:
        """Test case for create_user_tenant_mapping_v1_users_tenant_mapping_post

        Create User Tenant Mapping
        """
        pass


if __name__ == '__main__':
    unittest.main()
