# coding: utf-8

"""
onelens-backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from onelens_backend_client.models.message_part import MessagePart


class TestMessagePart(unittest.TestCase):
    """MessagePart unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MessagePart:
        """Test MessagePart
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `MessagePart`
        """
        model = MessagePart()
        if include_optional:
            return MessagePart(
                type = 'TEXT',
                value = None
            )
        else:
            return MessagePart(
                type = 'TEXT',
                value = None,
        )
        """

    def testMessagePart(self):
        """Test MessagePart"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
