# coding: utf-8

"""
onelens-backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from onelens_backend_client.models.update_feature_status_request import (
    UpdateFeatureStatusRequest,
)


class TestUpdateFeatureStatusRequest(unittest.TestCase):
    """UpdateFeatureStatusRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateFeatureStatusRequest:
        """Test UpdateFeatureStatusRequest
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `UpdateFeatureStatusRequest`
        """
        model = UpdateFeatureStatusRequest()
        if include_optional:
            return UpdateFeatureStatusRequest(
                tenant_id = '',
                id = '',
                is_enabled = True
            )
        else:
            return UpdateFeatureStatusRequest(
                tenant_id = '',
                id = '',
                is_enabled = True,
        )
        """

    def testUpdateFeatureStatusRequest(self):
        """Test UpdateFeatureStatusRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
