# coding: utf-8

"""
onelens-backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest



class TestCurDataAggregationType(unittest.TestCase):
    """CurDataAggregationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCurDataAggregationType(self):
        """Test CurDataAggregationType"""
        # inst = CurDataAggregationType()


if __name__ == "__main__":
    unittest.main()
