# coding: utf-8

"""
onelens-backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from onelens_backend_client.models.get_policy_tickets_export_request import (
    GetPolicyTicketsExportRequest,
)


class TestGetPolicyTicketsExportRequest(unittest.TestCase):
    """GetPolicyTicketsExportRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPolicyTicketsExportRequest:
        """Test GetPolicyTicketsExportRequest
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GetPolicyTicketsExportRequest`
        """
        model = GetPolicyTicketsExportRequest()
        if include_optional:
            return GetPolicyTicketsExportRequest(
                pagination = onelens_backend_client.models.pagination_params.PaginationParams(
                    page = 56, 
                    page_size = 56, ),
                filters = [
                    {field=policy_id, operator=equals, value=4467d3a5-d806-4389-8b87-ada5b6f9ff30}
                    ],
                sort_criteria = {direction=asc, field=policy_name},
                selected_fields = [
                    onelens_backend_client.models.tickets_selected_field.TicketsSelectedField(
                        field = '', 
                        category = null, )
                    ],
                file_extension = 'csv',
                tenant_id = ''
            )
        else:
            return GetPolicyTicketsExportRequest(
                filters = [
                    {field=policy_id, operator=equals, value=4467d3a5-d806-4389-8b87-ada5b6f9ff30}
                    ],
                tenant_id = '',
        )
        """

    def testGetPolicyTicketsExportRequest(self):
        """Test GetPolicyTicketsExportRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
