# coding: utf-8

"""
    onelens-backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.tenants_tenants_providers_api import TenantsTenantsProvidersApi


class TestTenantsTenantsProvidersApi(unittest.TestCase):
    """TenantsTenantsProvidersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TenantsTenantsProvidersApi()

    def tearDown(self) -> None:
        pass

    def test_create_tenant_provider_v1_tenants_tenant_id_providers_post(self) -> None:
        """Test case for create_tenant_provider_v1_tenants_tenant_id_providers_post

        Create Tenant Provider
        """
        pass

    def test_disable_tenant_provider_v1_tenants_tenant_id_providers_tenant_provider_id_disable_put(self) -> None:
        """Test case for disable_tenant_provider_v1_tenants_tenant_id_providers_tenant_provider_id_disable_put

        Disable Tenant Provider
        """
        pass

    def test_get_tenant_provider_v1_tenants_tenant_id_providers_tenant_provider_id_get(self) -> None:
        """Test case for get_tenant_provider_v1_tenants_tenant_id_providers_tenant_provider_id_get

        Get Tenant Provider
        """
        pass

    def test_get_tenant_providers_v1_tenants_fetch_post(self) -> None:
        """Test case for get_tenant_providers_v1_tenants_fetch_post

        Get Tenant Providers
        """
        pass

    def test_update_tenant_provider_v1_tenants_tenant_id_providers_tenant_provider_id_put(self) -> None:
        """Test case for update_tenant_provider_v1_tenants_tenant_id_providers_tenant_provider_id_put

        Update Tenant Provider
        """
        pass


if __name__ == '__main__':
    unittest.main()
