# coding: utf-8

"""
    onelens-backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from onelens_backend_client.models.get_tenant_anomaly_settings_api_request import GetTenantAnomalySettingsAPIRequest

class TestGetTenantAnomalySettingsAPIRequest(unittest.TestCase):
    """GetTenantAnomalySettingsAPIRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetTenantAnomalySettingsAPIRequest:
        """Test GetTenantAnomalySettingsAPIRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetTenantAnomalySettingsAPIRequest`
        """
        model = GetTenantAnomalySettingsAPIRequest()
        if include_optional:
            return GetTenantAnomalySettingsAPIRequest(
                pagination = onelens_backend_client.models.pagination_params.PaginationParams(
                    page = 56, 
                    page_size = 56, ),
                filters = onelens_backend_client.models.tenant_anomaly_setting_filters.TenantAnomalySettingFilters(
                    states = [
                        'ACTIVE'
                        ], )
            )
        else:
            return GetTenantAnomalySettingsAPIRequest(
        )
        """

    def testGetTenantAnomalySettingsAPIRequest(self):
        """Test GetTenantAnomalySettingsAPIRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
