# coding: utf-8

"""
onelens-backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from onelens_backend_client.api.policies_policy_template_packs_api import (
    PoliciesPolicyTemplatePacksApi,
)


class TestPoliciesPolicyTemplatePacksApi(unittest.TestCase):
    """PoliciesPolicyTemplatePacksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PoliciesPolicyTemplatePacksApi()

    def tearDown(self) -> None:
        pass

    def test_create_policy_template_pack(self) -> None:
        """Test case for create_policy_template_pack

        Create Policy Template Pack
        """
        pass

    def test_get_policy_template_pack(self) -> None:
        """Test case for get_policy_template_pack

        Get Policy Template Pack
        """
        pass

    def test_get_policy_template_packs(self) -> None:
        """Test case for get_policy_template_packs

        Get Policy Template Packs
        """
        pass


if __name__ == "__main__":
    unittest.main()
