# coding: utf-8

"""
    onelens-backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from onelens_backend_client.models.get_tenant_policies_with_settings_request import GetTenantPoliciesWithSettingsRequest

class TestGetTenantPoliciesWithSettingsRequest(unittest.TestCase):
    """GetTenantPoliciesWithSettingsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetTenantPoliciesWithSettingsRequest:
        """Test GetTenantPoliciesWithSettingsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetTenantPoliciesWithSettingsRequest`
        """
        model = GetTenantPoliciesWithSettingsRequest()
        if include_optional:
            return GetTenantPoliciesWithSettingsRequest(
                pagination = onelens_backend_client.models.pagination_params.PaginationParams(
                    page = 56, 
                    page_size = 56, ),
                filters = onelens_backend_client.models.tenant_policy_filters.TenantPolicyFilters(
                    search_query = '', 
                    parent_ptp_ids = [
                        ''
                        ], 
                    categories = [
                        'COST_SAVING'
                        ], 
                    providers = [
                        'AWS'
                        ], 
                    services = [
                        null
                        ], 
                    execution_types = [
                        'DETECTIVE'
                        ], ),
                tenant_id = ''
            )
        else:
            return GetTenantPoliciesWithSettingsRequest(
                tenant_id = '',
        )
        """

    def testGetTenantPoliciesWithSettingsRequest(self):
        """Test GetTenantPoliciesWithSettingsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
