# coding: utf-8

"""
    onelens-backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from onelens_backend_client.api.tenant_hierarchy_api import TenantHierarchyApi


class TestTenantHierarchyApi(unittest.TestCase):
    """TenantHierarchyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TenantHierarchyApi()

    def tearDown(self) -> None:
        pass

    def test_create_default_hierarchy(self) -> None:
        """Test case for create_default_hierarchy

        Create Default Hierarchy
        """
        pass

    def test_create_root_node(self) -> None:
        """Test case for create_root_node

        Create Root Node
        """
        pass

    def test_get_hierarchy_leaf_nodes(self) -> None:
        """Test case for get_hierarchy_leaf_nodes

        Get Hierarchy Leaf Nodes
        """
        pass


if __name__ == '__main__':
    unittest.main()
