# coding: utf-8

"""
    onelens-backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from onelens_backend_client.models.response_update_policy_template_response import ResponseUpdatePolicyTemplateResponse

class TestResponseUpdatePolicyTemplateResponse(unittest.TestCase):
    """ResponseUpdatePolicyTemplateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseUpdatePolicyTemplateResponse:
        """Test ResponseUpdatePolicyTemplateResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseUpdatePolicyTemplateResponse`
        """
        model = ResponseUpdatePolicyTemplateResponse()
        if include_optional:
            return ResponseUpdatePolicyTemplateResponse(
                data = onelens_backend_client.models.update_policy_template_response.UpdatePolicyTemplateResponse(
                    parent_ptp_id = '', 
                    title = '', 
                    alias = '', 
                    description = '', 
                    services = [
                        null
                        ], 
                    execution_type = null, 
                    details = null, 
                    id = '', 
                    state = null, 
                    category = null, 
                    provider = null, ),
                message = ''
            )
        else:
            return ResponseUpdatePolicyTemplateResponse(
                data = onelens_backend_client.models.update_policy_template_response.UpdatePolicyTemplateResponse(
                    parent_ptp_id = '', 
                    title = '', 
                    alias = '', 
                    description = '', 
                    services = [
                        null
                        ], 
                    execution_type = null, 
                    details = null, 
                    id = '', 
                    state = null, 
                    category = null, 
                    provider = null, ),
        )
        """

    def testResponseUpdatePolicyTemplateResponse(self):
        """Test ResponseUpdatePolicyTemplateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
