# coding: utf-8

"""
    onelens-backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from onelens_backend_client.models.get_cur_data_metrics_api_request import GetCURDataMetricsAPIRequest

class TestGetCURDataMetricsAPIRequest(unittest.TestCase):
    """GetCURDataMetricsAPIRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCURDataMetricsAPIRequest:
        """Test GetCURDataMetricsAPIRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCURDataMetricsAPIRequest`
        """
        model = GetCURDataMetricsAPIRequest()
        if include_optional:
            return GetCURDataMetricsAPIRequest(
                query = onelens_backend_client.models.cur_data_metrics_query.CURDataMetricsQuery(
                    name = '', 
                    dimension = '', 
                    measures = [
                        'sum_unblended_cost'
                        ], 
                    filters = [
                        onelens_backend_client.models.filter_criteria.FilterCriteria(
                            field = '', 
                            operator = 'equals', 
                            values = null, )
                        ], 
                    time_filter = onelens_backend_client.models.time_dimension.TimeDimension(
                        range = [
                            ''
                            ], 
                        granularity = onelens_backend_client.models.granularity.Granularity(
                            unit = 'days', 
                            value = 56, ), ), 
                    timezone = 'Asia/Kolkata', )
            )
        else:
            return GetCURDataMetricsAPIRequest(
                query = onelens_backend_client.models.cur_data_metrics_query.CURDataMetricsQuery(
                    name = '', 
                    dimension = '', 
                    measures = [
                        'sum_unblended_cost'
                        ], 
                    filters = [
                        onelens_backend_client.models.filter_criteria.FilterCriteria(
                            field = '', 
                            operator = 'equals', 
                            values = null, )
                        ], 
                    time_filter = onelens_backend_client.models.time_dimension.TimeDimension(
                        range = [
                            ''
                            ], 
                        granularity = onelens_backend_client.models.granularity.Granularity(
                            unit = 'days', 
                            value = 56, ), ), 
                    timezone = 'Asia/Kolkata', ),
        )
        """

    def testGetCURDataMetricsAPIRequest(self):
        """Test GetCURDataMetricsAPIRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
