# coding: utf-8

"""
    onelens-backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from onelens_backend_client.models.service_catalog_response import ServiceCatalogResponse

class TestServiceCatalogResponse(unittest.TestCase):
    """ServiceCatalogResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceCatalogResponse:
        """Test ServiceCatalogResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceCatalogResponse`
        """
        model = ServiceCatalogResponse()
        if include_optional:
            return ServiceCatalogResponse(
                services = [
                    onelens_backend_client.models.service_catalog.ServiceCatalog(
                        id = '', 
                        name = '', 
                        product_code = '', 
                        display_name = '', 
                        description = '', 
                        resource_types = {
                            'key' : onelens_backend_client.models.resource_types.ResourceTypes(
                                resource_type = '', 
                                resource_table = '', 
                                select_columns = [
                                    ''
                                    ], 
                                aws_url_template = '', 
                                relationship_config = [
                                    onelens_backend_client.models.relationship_config_item.RelationshipConfigItem(
                                        relationship_type = '', 
                                        join = onelens_backend_client.models.join.Join(
                                            current_table_column = '', 
                                            join_table = '', 
                                            join_table_column = '', ), )
                                    ], )
                            }, 
                        features = onelens_backend_client.models.features.Features(
                            enable_in_policy = True, 
                            enable_in_anomalies = True, ), )
                    ]
            )
        else:
            return ServiceCatalogResponse(
                services = [
                    onelens_backend_client.models.service_catalog.ServiceCatalog(
                        id = '', 
                        name = '', 
                        product_code = '', 
                        display_name = '', 
                        description = '', 
                        resource_types = {
                            'key' : onelens_backend_client.models.resource_types.ResourceTypes(
                                resource_type = '', 
                                resource_table = '', 
                                select_columns = [
                                    ''
                                    ], 
                                aws_url_template = '', 
                                relationship_config = [
                                    onelens_backend_client.models.relationship_config_item.RelationshipConfigItem(
                                        relationship_type = '', 
                                        join = onelens_backend_client.models.join.Join(
                                            current_table_column = '', 
                                            join_table = '', 
                                            join_table_column = '', ), )
                                    ], )
                            }, 
                        features = onelens_backend_client.models.features.Features(
                            enable_in_policy = True, 
                            enable_in_anomalies = True, ), )
                    ],
        )
        """

    def testServiceCatalogResponse(self):
        """Test ServiceCatalogResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
