# coding: utf-8

"""
onelens-backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from onelens_backend_client.models.get_tenants_request import GetTenantsRequest


class TestGetTenantsRequest(unittest.TestCase):
    """GetTenantsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetTenantsRequest:
        """Test GetTenantsRequest
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GetTenantsRequest`
        """
        model = GetTenantsRequest()
        if include_optional:
            return GetTenantsRequest(
                filters = onelens_backend_client.models.tenant_filters.TenantFilters(
                    names = null, 
                    tenant_states = null, )
            )
        else:
            return GetTenantsRequest(
        )
        """

    def testGetTenantsRequest(self):
        """Test GetTenantsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
