# coding: utf-8

"""
onelens-backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest



class TestTicketCategory(unittest.TestCase):
    """TicketCategory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTicketCategory(self):
        """Test TicketCategory"""
        # inst = TicketCategory()


if __name__ == "__main__":
    unittest.main()
