# coding: utf-8

"""
onelens-backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from onelens_backend_client.models.data_retriever_request import DataRetrieverRequest


class TestDataRetrieverRequest(unittest.TestCase):
    """DataRetrieverRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataRetrieverRequest:
        """Test DataRetrieverRequest
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DataRetrieverRequest`
        """
        model = DataRetrieverRequest()
        if include_optional:
            return DataRetrieverRequest(
                query = onelens_backend_client.models.data_retriever_query.DataRetrieverQuery(
                    measures = [
                        ''
                        ], 
                    dimensions = [
                        ''
                        ], 
                    filters = [
                        onelens_backend_client.models.query_filters.QueryFilters(
                            dimension = '', 
                            operator = '', 
                            values = [
                                ''
                                ], )
                        ], 
                    time_dimensions = [
                        onelens_backend_client.models.time_dimension.TimeDimension(
                            dimension = '', 
                            date_range = [
                                ''
                                ], 
                            compare_date_range = [
                                null
                                ], 
                            granularity = '', )
                        ], 
                    segments = [
                        ''
                        ], 
                    limit = 56, 
                    total = True, 
                    offset = 56, 
                    order = [
                        'asc'
                        ], 
                    timezone = '', 
                    renew_query = True, 
                    ungrouped = True, )
            )
        else:
            return DataRetrieverRequest(
                query = onelens_backend_client.models.data_retriever_query.DataRetrieverQuery(
                    measures = [
                        ''
                        ], 
                    dimensions = [
                        ''
                        ], 
                    filters = [
                        onelens_backend_client.models.query_filters.QueryFilters(
                            dimension = '', 
                            operator = '', 
                            values = [
                                ''
                                ], )
                        ], 
                    time_dimensions = [
                        onelens_backend_client.models.time_dimension.TimeDimension(
                            dimension = '', 
                            date_range = [
                                ''
                                ], 
                            compare_date_range = [
                                null
                                ], 
                            granularity = '', )
                        ], 
                    segments = [
                        ''
                        ], 
                    limit = 56, 
                    total = True, 
                    offset = 56, 
                    order = [
                        'asc'
                        ], 
                    timezone = '', 
                    renew_query = True, 
                    ungrouped = True, ),
        )
        """

    def testDataRetrieverRequest(self):
        """Test DataRetrieverRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
