# coding: utf-8

"""
onelens-backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from onelens_backend_client.models.get_policy_ticket_stats_request_v2 import (
    GetPolicyTicketStatsRequestV2,
)


class TestGetPolicyTicketStatsRequestV2(unittest.TestCase):
    """GetPolicyTicketStatsRequestV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPolicyTicketStatsRequestV2:
        """Test GetPolicyTicketStatsRequestV2
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GetPolicyTicketStatsRequestV2`
        """
        model = GetPolicyTicketStatsRequestV2()
        if include_optional:
            return GetPolicyTicketStatsRequestV2(
                metric = 'SUM_SAVINGS',
                filters = [
                    {field=policy_id, operator=equals, value=4467d3a5-d806-4389-8b87-ada5b6f9ff30}
                    ],
                group = onelens_backend_client.models.group_by_option.GroupByOption(
                    type = null, 
                    value = null, ),
                sub_group = onelens_backend_client.models.sub_group_by_option.SubGroupByOption(
                    type = null, 
                    value = null, ),
                limit_items = True,
                item_count = 56,
                tenant_id = ''
            )
        else:
            return GetPolicyTicketStatsRequestV2(
                metric = 'SUM_SAVINGS',
                filters = [
                    {field=policy_id, operator=equals, value=4467d3a5-d806-4389-8b87-ada5b6f9ff30}
                    ],
                tenant_id = '',
        )
        """

    def testGetPolicyTicketStatsRequestV2(self):
        """Test GetPolicyTicketStatsRequestV2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
