# coding: utf-8

"""
    onelens-backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_policy_templates_response import GetPolicyTemplatesResponse

class TestGetPolicyTemplatesResponse(unittest.TestCase):
    """GetPolicyTemplatesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPolicyTemplatesResponse:
        """Test GetPolicyTemplatesResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPolicyTemplatesResponse`
        """
        model = GetPolicyTemplatesResponse()
        if include_optional:
            return GetPolicyTemplatesResponse(
                pagination = openapi_client.models.pagination_fields.PaginationFields(
                    total_items = 56, 
                    total_pages = 56, 
                    current_page = 56, 
                    page_size = 56, ),
                policy_templates = [
                    openapi_client.models.policy_template.PolicyTemplate(
                        parent_ptp_id = '', 
                        title = '', 
                        description = '', 
                        services = [
                            null
                            ], 
                        execution_type = null, 
                        details = null, 
                        id = '', 
                        state = null, 
                        category = null, 
                        provider = null, )
                    ]
            )
        else:
            return GetPolicyTemplatesResponse(
                pagination = openapi_client.models.pagination_fields.PaginationFields(
                    total_items = 56, 
                    total_pages = 56, 
                    current_page = 56, 
                    page_size = 56, ),
                policy_templates = [
                    openapi_client.models.policy_template.PolicyTemplate(
                        parent_ptp_id = '', 
                        title = '', 
                        description = '', 
                        services = [
                            null
                            ], 
                        execution_type = null, 
                        details = null, 
                        id = '', 
                        state = null, 
                        category = null, 
                        provider = null, )
                    ],
        )
        """

    def testGetPolicyTemplatesResponse(self):
        """Test GetPolicyTemplatesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
