# coding: utf-8

"""
onelens-backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from onelens_backend_client.models.saved_view_item_payload_input_sort_criteria import (
    SavedViewItemPayloadInputSortCriteria,
)


class TestSavedViewItemPayloadInputSortCriteria(unittest.TestCase):
    """SavedViewItemPayloadInputSortCriteria unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SavedViewItemPayloadInputSortCriteria:
        """Test SavedViewItemPayloadInputSortCriteria
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SavedViewItemPayloadInputSortCriteria`
        """
        model = SavedViewItemPayloadInputSortCriteria()
        if include_optional:
            return SavedViewItemPayloadInputSortCriteria(
                var_field = '',
                direction = 'asc'
            )
        else:
            return SavedViewItemPayloadInputSortCriteria(
                var_field = '',
                direction = 'asc',
        )
        """

    def testSavedViewItemPayloadInputSortCriteria(self):
        """Test SavedViewItemPayloadInputSortCriteria"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
