# coding: utf-8

"""
onelens-backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from onelens_backend_client.api.saved_views_api import SavedViewsApi


class TestSavedViewsApi(unittest.TestCase):
    """SavedViewsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SavedViewsApi()

    def tearDown(self) -> None:
        pass

    def test_create_saved_view(self) -> None:
        """Test case for create_saved_view

        Create a new saved view.
        """
        pass

    def test_delete_saved_view(self) -> None:
        """Test case for delete_saved_view

        Delete a saved view.
        """
        pass

    def test_get_saved_views(self) -> None:
        """Test case for get_saved_views

        Get saved views.
        """
        pass

    def test_mark_saved_view_as_default(self) -> None:
        """Test case for mark_saved_view_as_default

        Mark a saved view as default.
        """
        pass

    def test_update_saved_view(self) -> None:
        """Test case for update_saved_view

        Update a saved view.
        """
        pass


if __name__ == "__main__":
    unittest.main()
