# coding: utf-8

"""
onelens-backend

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from onelens_backend_client.models.get_saved_views_request import GetSavedViewsRequest


class TestGetSavedViewsRequest(unittest.TestCase):
    """GetSavedViewsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSavedViewsRequest:
        """Test GetSavedViewsRequest
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GetSavedViewsRequest`
        """
        model = GetSavedViewsRequest()
        if include_optional:
            return GetSavedViewsRequest(
                filters = [
                    {field=policy_id, operator=equals, value=4467d3a5-d806-4389-8b87-ada5b6f9ff30}
                    ],
                sort_criteria = {direction=asc, field=policy_name},
                ol_user_id = '',
                tenant_id = ''
            )
        else:
            return GetSavedViewsRequest(
                ol_user_id = '',
                tenant_id = '',
        )
        """

    def testGetSavedViewsRequest(self):
        """Test GetSavedViewsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
